//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Question3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Income
    {
        public int id { get; set; }
        public decimal Amount { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
